language: java
dist: xenial

services:
  - docker

branches:
  only:
    - master

install:
  - set -e
  - nohup docker pull localstack/localstack > /dev/null &
  - nohup docker pull lambci/lambda:java11 > /dev/null &

script:
  - set -e
  - mvn -q -DskipTests test
  - make test
  - docker ps -a

notifications:
  email: false
